### ISSUE TITLE
null_req test fails.

### ISSUE THREAD

**Issue by hyoklee** [DataLib-ECP/vol-log-based#3]
See the artifact from my GitHub Action [1].

```
FAIL: null_req
==============

*** TESTING CXX    null_req: Call H5Dwrite with empty selection
HDF5-DIAG: Error detected in HDF5 (1.13.0-7) MPI-process 0:
  #000: H5VL.c line 87 in H5VLregister_connector(): library initialization failed
    major: Function entry/exit
    minor: Unable to initialize object
  #001: H5.c line 279 in H5_init_library(): unable to initialize vol interface
    major: Function entry/exit
    minor: Unable to initialize object
  #002: H5VLint.c line 198 in H5VL_init_phase2(): unable to set default VOL connector
    major: Virtual Object Layer
    minor: Can't set value
  #003: H5VLint.c line 440 in H5VL__set_def_conn(): can't register connector
    major: Virtual Object Layer
    minor: Unable to register new ID
  #004: H5VLint.c line 1372 in H5VL__register_connector_by_name(): unable to load VOL connector
    major: Virtual Object Layer
    minor: Unable to initialize object
HDF5-DIAG: Error detected in HDF5 (1.13.0-7) MPI-process 0:
  #000: H5Pfapl.c line 6114 in H5Pset_vol(): not a file VOL ID
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.13.0-7) MPI-process 0:
  #000: H5D.c line 1225 in H5Dwrite(): can't synchronously write data
    major: Dataset
    minor: Write failed
  #001: H5D.c line 1172 in H5D__write_api_common(): can't write data
    major: Dataset
    minor: Write failed
  #002: H5VLcallback.c line 2181 in H5VL_dataset_write(): dataset write failed
    major: Virtual Object Layer
    minor: Write failed
  #003: H5VLcallback.c line 2148 in H5VL__dataset_write(): dataset write failed
    major: Virtual Object Layer
    minor: Write failed
  #004: H5VLnative_dataset.c line 345 in H5VL__native_dataset_write(): can't write data
    major: Dataset
    minor: Write failed
  #005: H5Dio.c line 374 in H5D__write(): src and dest dataspaces have different number of elements selected
    major: Invalid arguments to routine
    minor: Bad value
Error at line 69 in null_req.cpp:
fail with 1 mismatches.
FAIL null_req (exit status: 1)
```
[1] https://github.com/hyoklee/vol-log-based/actions/runs/1397442070

**Comment by khou2020** [comment]
Should be working now.

**Comment by hyoklee** [comment]
@khou2020, null_req test still fails when you set 

```export HDF5_VOL_CONNECTOR="LOG under_vol=0;under_info={}"```

Is it expected?

**Comment by khou2020** [comment]
I cannot recreate the issue. Can you provide the full run steps?

**Comment by hyoklee** [comment]
Step:
Add one line ```export HDF5_VOL_CONNECTOR="LOG under_vol=0;under_info={}"``` before ```make check``` in your ubuntu_mpich.yml.

Here's an example:
https://github.com/hyoklee/vol-log-based/blob/master/.github/workflows/ubuntu_mpich2.yml

Result:
https://github.com/hyoklee/vol-log-based/actions/runs/1426026041

**Comment by khou2020** [comment]
You need to set HDF5_PLUGIN_PATH to the folder containing the shared library of log-based VOL.
export HDF5_PLUGIN_PATH=${WORKDIR}/src/.lib
